### ISSUE TITLE
Kaliel's Tracker

### ISSUE THREAD

**Issue by phuze** [ipzaur/ipmythictimer#15]
`KT_ObjectiveTracker_Expand` is no longer a function of [Kaliel's Tracker](https://www.curseforge.com/wow/addons/kaliels-tracker), and as a result, iPMythicTimer is constantly throwing an error in M+.

```lua
Message: .../AddOns/iPMythicTimer/cooperation/kalielsTracker.lua:19: hooksecurefunc(): KT_ObjectiveTracker_Expand is not a function
Time: Thu Sep 19 23:25:02 2024
Count: 11
Stack: .../AddOns/iPMythicTimer/cooperation/kalielsTracker.lua:19: hooksecurefunc(): KT_ObjectiveTracker_Expand is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/iPMythicTimer/cooperation/kalielsTracker.lua"]:19: in function `KalielsTrackerFix'
[string "@Interface/AddOns/iPMythicTimer/main.lua"]:614: in function <Interface/AddOns/iPMythicTimer/main.lua:580>
[string "=[C]"]: in function `Activate'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua"]:669: in function `CheckTimers'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua"]:623: in function <...jectiveTracker/Blizzard_ScenarioObjectiveTracker.lua:620>
```

I have no idea when this feature was added as I only recently installed it, but Kaliel's Tracker has a baked-in feature which automatically closes the quest panel on entering an instance. Please consider removing the cooperation code for Kaliel's Tracker entirely, or otherwise updating to support the latest addon hooks.

![image](https://github.com/user-attachments/assets/23181680-52a9-4395-97cf-53f2cc46c691)

I took a quick peek at the code for Kaliel's Tracker, and if you wanted to update your cooperation logic, then you'll probably want to take a look at `ObjectiveTracker_Toggle()`. But honestly, it'd probably make more sense just to drop this code entirely.

**Note:** for anyone who may be reading this -- you can fix the issue temporarily, by commenting out [this line](https://github.com/ipzaur/ipmythictimer/blob/master/main.lua#L635). IE:

```lua
--Addon:KalielsTrackerFix()
```

**Comment by phuze** [comment]
@ipzaur

**Comment by phuze** [comment]
Project is dead. Use [WarpDeplete](https://www.curseforge.com/wow/addons/warpdeplete) instead.

**Comment by ipzaur** [comment]
Hi, @phuze !
In early versions, "Kaliel's Tracker" used its own function to collapse and expand Objectives Panel (includes the standard timer). During a run of key, I was collapse quests. But "Kaliel's" sometimes had a bug that it would periodically expand its panel with the standard timer. I had to make such a hook.
I myself do not use "Kaliel's Tracker", the fix was at the request of users.
Anyway, thanks for the report and detailed description of the problem. I will try to a fix it in the near future.

**Comment by ipzaur** [comment]
As it turns out, "Kaliel's Tracker" is still using its own function to collapse ObjectiveTracker. It's just that it's now renamed to ‘KT_ObjectiveTrackerFrame:SetCollapsed’. Anyway, the bug is now fixed. Thanks again for the report and I apologise for seeing this Issue late ;)
