### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by layday** [ipzaur/ipmythictimer#18]
Hi and thanks for this add-on - I was wondering whether you'd be interested in releasing new add-on versions here on GitHub in addition to Curse and Wago. Tools like [packager](https://github.com/BigWigsMods/packager) can do this out of the box for you.

**Comment by ipzaur** [comment]
@layday 
Hi! This is interesting. Thanks. I will look into this tool and try to release the addon on GitHub :)
