### ISSUE TITLE
warfronts error

### ISSUE THREAD

**Issue by lkraMl** [ipzaur/ipmythictimer#5]
18x iPMythicTimer\main.lua:151: attempt to index field 'trash' (a nil value)
[string "@iPMythicTimer\main.lua"]:151: in function `UpdateProgress'
[string "@iPMythicTimer\main.lua"]:451: in function `OnEvent'
[string "@iPMythicTimer\frames\main.lua"]:46: in function <iPMythicTimer\frames\main.lua:45>

Locals:
self = <table> {
 GetEnemyForces = <function> defined @iPMythicTimer\main.lua:31
 MoveElement = <function> defined @iPMythicTimer\options.lua:114
 DECOR_FONT = "iPMythicTimer\media\RobotoCondensed-Regular.ttf"
 RecalcElem = <function> defined @iPMythicTimer\options.lua:257
 EnemyDied = <function> defined @iPMythicTimer\main.lua:91
 UpdateProgress = <function> defined @iPMythicTimer\main.lua:145
 fDebug = IPMTDebug {
 }
 OnShow = <function> defined @iPMythicTimer\main.lua:503
 StartDragging = <function> defined @iPMythicTimer\utility.lua:21
 SetFont = <function> defined @iPMythicTimer\options.lua:67
 keyActive = false
 MDTdungeon = <table> {
 }
 deathRowHeight = 24
 OnBossesEnter = <function> defined @iPMythicTimer\main.lua:213
 season = <table> {
 }
 GetForcesFromMDT = <function> defined @iPMythicTimer\cooperation\mdt.lua:41
 StartFontSize = <function> defined @iPMythicTimer\options.lua:295
 PROGRESS_DIRECTION_ASC = 1
 OnTimerEnter = <function> defined @iPMythicTimer\main.lua:183
 ACOUSTIC_STRING_X3 = "iPMythicTimer\media\acoustic_string_x3.mp3"
 SetFontSize = <function> defined @iPMythicTimer\options.lua:280
 ToggleHelp = <function> defined @iPMythicTimer\help.lua:3
 isCustomizing = false
 ShowOptions = <function> defined @iPMythicTimer\options.lua:401
 defaultSize = <table> {
 }
 ToggleCustomize = <function> defined @iPMythicTimer\options.lua:327
 ToggleVisible = <function> defined @iPMythicTimer\options.lua:318
 SetOpacity = <function> defined @iPMythicTimer\options.lua:43
 fDeaths = IPMTDeaths {
 }
 OnAffixEnter = <function> defined @iPMythicTimer\main.lua:229
 FONT_ROBOTO = "iPMythicTimer\media\RobotoCondensed-Regular.ttf"
 frameInfo = <table> {
 }
 toggleMapbutton = <function> defined @iPMythicTimer\options.lua:391
 DECOR_FONTSIZE_DELTA = 0
 CloseOptions = <function> defined @iPMythicTimer\options.lua:439
 LoadOptions = <function> defined @iPMythicTimer\options.lua:137
 ToggleOptions = <function> defined @iPMythicTimer\options.lua:384
 SelectFont = <function> defined @iPMythicTimer\options.lua:247
 backdrop = <table> {
 }
 version = 1200
 localization = <table> {
 }
 InitIcon = <function> defined @iPMythicTimer\frames\mapbut.lua:3
 StartAddon = <function> defined @iPMythicTimer\iPMythicTimer.lua:46
 PROGRESS_FORMAT_PERCENT = 1
 FillDeathRow = <function> defined @iPMythicTimer\frames\deaths.lua:113
 deaths = <table> {
 }
 DB = <table> {
 }
 StopDragging = <function> defined @iPMythicTimer\utility.lua:26
 Init = <function> defined @iPMythicTimer\main.lua:479
 ShowPrognosis = <function> defined @iPMythicTimer\prognosis.lua:44
 FONT_ROBOTO_LIGHT = "iPMythicTimer\media\RobotoCondensed-Light.ttf"
 CleanDB = <function> defined @iPMythicTimer\options.lua:30
 OpenSettingsFromPanel = <function> defined @iPMythicTimer\options.lua:540
 ToggleDBTooltip = <function> defined @iPMythicTimer\options.lua:33
 OnUpdate = <function> defined @iPMythicTimer\main.lua:240
 Round = <function> defined @iPMythicTimer\utility.lua:10
 HideHelp = <function> defined @iPMythicTimer\frames\help.lua:229
 fMain = IPMTMain {
 }
 panel = IPMTOptionsPanel {
 }
 SetScale = <function> defined @iPMythicTimer\options.lua:55
 SetProgressFormat = <function> defined @iPMythicTimer\options.lua:88
 defaultOptions = <table> {
 }
 RestoreOptions = <function> defined @iPMythicTimer\options.lua:453
 AFFIX_TEEMING = 5
 ShowHelp = <function> defined

**Comment by ipzaur** [comment]
Hello! Sorry for late reply, I just saw this issue. Is it still actual or I can close it?
